import React from "react";
// component
import { Row } from "components/Layout";
import { Text } from "components/Text";
import { Hidden } from "components/Hidden";
import { useLinkItem } from "components/hoc";
import { SliderOptions, useSlider } from "components/Slider";
// hook
import { useRouter } from "hooks";
// feature
import { BlogItem } from "widgets/BlogItem";
// types
import { BlogViewItemProps } from "components/Card";
import { BlogItemInterface } from "types/model/blog/interface";
// assets
import { AiOutlineRight } from "react-icons/ai";
// styled component
import {
	VisitWrapper,
	BlogTitleView,
	SliderWrapper,
	BlogViewItemWrapper,
} from "../BlogView.style";
import { BREAKPOINTS } from "theme/base";
// ----------------------------------------------------
// component generated by hoc
const options: SliderOptions = {
	speed: 600,
	slidesPerView: "auto",
	freeMode: true,
	pagination: {
		clickable: true,
		// eslint-disable-next-line @typescript-eslint/no-unused-vars
		renderBullet: (_, className) => {
			return '<span class="bulletContainer ' + className + '"> </span>';
		},
	},
};

const MenuItem = useLinkItem(VisitWrapper);
const BlogViewSlider = useSlider<BlogItemInterface>(
	BlogItem,
	options,
	SliderWrapper
);
const { xs } = BREAKPOINTS;

const BlogView: React.FC<BlogViewItemProps> = ({
	category,
	categoryId,
	categoryData,
	loading,
}) => {
	const { move } = useRouter();
	return (
		<BlogViewItemWrapper>
			<Row
				justifyContent="space-between"
				alignItems="center"
				padding="0 0 5px 0"
			>
				<BlogTitleView>
					<Row justifyContent="space-between">
						<Text textTransform="uppercase" fontSize={15} fontWeight={900}>
							{category}
						</Text>
						<Hidden wShow={[xs]}>
							<MenuItem
								title="View All"
								alignHorizontal="center"
								iconSlot="end"
								icon={<AiOutlineRight size={8} />}
								handleClick={() => move("/", { tag: categoryId })}
							/>
						</Hidden>
					</Row>
				</BlogTitleView>
				<Hidden wHide={[xs]}>
					<MenuItem
						title="View All"
						alignHorizontal="center"
						iconSlot="end"
						icon={<AiOutlineRight size={8} />}
						handleClick={() => move("/", { tag: categoryId })}
					/>
				</Hidden>
			</Row>

			<BlogViewSlider
				sliderData={categoryData}
				itemOptions={{ badgeColor: "primary.regular", loading }}
			/>
		</BlogViewItemWrapper>
	);
};

export default BlogView;
