// assets
import brandMenu1 from "assets/images/temp/brandMenu1.jpg";
import brandMenu2 from "assets/images/temp/brandMenu2.jpg";
import brandMenu3 from "assets/images/temp/brandMenu3.png";
import brandMenu4 from "assets/images/temp/brandMenu4.jpg";
import brandMenu5 from "assets/images/temp/brandMenu5.png";
import brandMenu6 from "assets/images/temp/brandMenu6.jpg";
import brandMenu7 from "assets/images/temp/brandMenu7.jpg";
import brandMenu8 from "assets/images/temp/brandMenu8.jpg";
// --------------------------------------------------------------------
const brandData = [
  { title: "13 Lives", href: "/" },
  { title: "1Up Nutrition", href: "/" },
  { title: "3D", href: "/" },
  { title: "60 Day Body Challenge", href: "/" },
  { title: "Abundant Natural Health", href: "/" },
  { title: "Alien Supps", href: "/" },
  { title: "Alien Supps", href: "/" },
  { title: "B Raw", href: "/" },
  { title: "Bach", href: "/" },
  { title: "B Raw", href: "/" },
  { title: "Bach", href: "/" },
  { title: "Caruso's Natural Health(Totally Natural)", href: "/" },
  { title: "Cell Charge", href: "/" },
  { title: "DarkSide Supps", href: "/" },
  { title: "Day One Performance", href: "/" },
  { title: "Eagle Nutrition", href: "/" },
  { title: "EHP Labs", href: "/" },
  { title: "Faction Labs", href: "/" },
  { title: "Fangs", href: "/" },
  { title: "G Fuel", href: "/" },
  { title: "Gamma labs", href: "/" },
  { title: "G Fuel", href: "/" },
  { title: "Gamma labs", href: "/" },
  { title: "G Fuel", href: "/" },
  { title: "Gamma labs", href: "/" },
  { title: "Happy Flora", href: "/" },
  { title: "Harmony", href: "/" },
  { title: "I Eat Protein", href: "/" },
  { title: "In2 Performance", href: "/" },
  { title: "JD Nutraceuticals", href: "/" },
  { title: "Jocko Fuel", href: "/" },
  { title: "JD Nutraceuticals", href: "/" },
  { title: "Jocko Fuel", href: "/" },
  { title: "keetz", href: "/" },
  { title: "Kelloggs", href: "/" },
  { title: "labeada Nutrition", href: "/" },
  { title: "Lean Body For Her", href: "/" },
  { title: "Macro Mike Madness Nutrition", href: "/" },
  { title: "Madness Nutrition", href: "/" },
  { title: "Macro Mike Madness Nutrition", href: "/" },
  { title: "Madness Nutrition", href: "/" },
  { title: "Macro Mike Madness Nutrition", href: "/" },
  { title: "Madness Nutrition", href: "/" },
  { title: "NatHealth Solutions", href: "/" },
  { title: "Natural Health Company", herf: "/" },
  { title: "NatHealth Solutions", href: "/" },
  { title: "Natural Health Company", herf: "/" },
  { title: "NatHealth Solutions", href: "/" },
  { title: "Natural Health Company", herf: "/" },
  { title: "Oatein", herf: "/" },
  { title: "Obvi", herf: "/" },
  { title: "PBCo", herf: "/" },
  { title: "Peak Chocolate", herf: "/" },
  { title: "Quest Nutrition", herf: "/" },
  { title: "Rapid Supplements", herf: "/" },
  { title: "Red Bull", herf: "/" },
  { title: "Rapid Supplements", herf: "/" },
  { title: "Red Bull", herf: "/" },
  { title: "Rapid Supplements", herf: "/" },
  { title: "Red Bull", herf: "/" },
  { title: "SAN Nutrition", herf: "/" },
  { title: "Science in Sport", herf: "/" },
  { title: "Temole", herf: "/" },
  { title: "TF7 Labs", herf: "/" },
  { title: "Ulti-Gen", herf: "/" },
  { title: "Universal Nutrition", herf: "/" },
  { title: "Vantage Strength", herf: "/" },
  { title: "Accessories", herf: "/" },
  { title: "Veego", herf: "/" },
  { title: "Wagner", herf: "/" },
  { title: "Walden Farms", herf: "/" },
  { title: "Youthful Living", herf: "/" },
  { title: "Yum Natural", herf: "/" },
  { title: "Zen", herf: "/" },
];
const brandList = [
  brandMenu8,
  brandMenu7,
  brandMenu6,
  brandMenu5,
  brandMenu4,
  brandMenu3,
  brandMenu2,
  brandMenu1,
];
export default { brandData, brandList };
