const menuLinkData = [
  {
    title: "Sports Nutrition",
    url: "#",
    items: [
      { title: "Pre Workout", url: "#" },
      { title: "Amino Acids", url: "#" },
      { title: "Creatine", url: "#" },
      { title: "Carbohydrates", url: "#" },
      { title: "Nitirc Oxide Boosters", url: "#" },
      { title: "Post Worrkout", url: "#" },
      { title: "Endurance", url: "#" },
      { title: "Nootropics", url: "#" },
      { title: "Intra Workout", url: "#" },
    ],
  },
  {
    title: "More Categories",
    url: "#",
    items: [
      { title: "Workout Apparel", url: "#" },
      { title: "Accessories", url: "#" },
      { title: "Healthy Snacks & Foods", url: "#" },
      { title: "Test Boosters", url: "#" },
      { title: "Supp Awards", url: "#" },
      { title: "Genetix Pure Series", url: "#" },
      { title: "Genetix Protein", url: "#" },
      { title: "Vegan Fat Burners", url: "#" },
    ],
  },
  {
    title: "Health & Vitamins",
    url: "#",
    items: [
      { title: "General Health", url: "#" },
      { title: "Vitamins & Minerals", url: "#" },
      { title: "Sleep Aids", url: "#" },
      { title: "Hormonal Support", url: "#" },
    ],
  },
  {
    title: "Weight Loss",
    url: "#",
    items: [
      { title: "Fat Burners", url: "#" },
      { title: "Womens Weight Loss", url: "#" },
      { title: "L-Carnitine", url: "#" },
      { title: "Acetyl L-Carnitine", url: "#" },
      { title: "Fat Metabolisers", url: "#" },
      { title: "Keto", url: "#" },
      { title: "Appetite Suppressant", url: "#" },
      { title: "CLA", url: "#" },
      { title: "Diuretics", url: "#" },
    ],
  },
  {
    title: "Protein",
    url: "#",
    items: [
      { title: "Whey Protein Blends", url: "#" },
      { title: "Whey Protein Isolate", url: "#" },
      { title: "Weight Gainers", url: "#" },
      { title: "Weight Loss Protein", url: "#" },
      { title: "Natural Protein", url: "#" },
      { title: "Plant Based Protein", url: "#" },
      { title: "Womens Protein", url: "#" },
      { title: "Protein Bar & Cookies", url: "#" },
      { title: "Casein Protein", url: "#" },
      { title: "Pea Protein", url: "#" },
      { title: "Post Workout Protein", url: "#" },
      { title: "Rice Protein", url: "#" },
      { title: "Soy Protein", url: "#" },
      { title: "Whey Concentrate (WPC)", url: "#" },
      { title: "Whey Hydrolysate", url: "#" },
      { title: "Beef Protein", url: "#" },
      { title: "Egg Protein", url: "#" },
      { title: "Meal Replacement", url: "#" },
    ],
  },
];
export default menuLinkData;
