export { default as AccountIcon } from "./account";
export { default as CartIcon } from "./cart";
export { default as CheckoutIcon, ShoppingBagIcon } from "./checkout";
export { default as LocationIcon, LocationIcon2 } from "./location";
export { default as PhoneIcon } from "./phone";
export { default as RefreshIcon } from "./refresh";
export { default as RewardsIcon } from "./rewards";
export { default as SearchIcon } from "./search";
export { default as SocialIcon } from "./social";
export { default as SendIcon } from "./send";
export { default as StarIcons } from "./star";
export { default as SpeedIcon } from "./speed";
export { default as BodyIcon } from "./body";
export { default as MuscleIcon } from "./muscle";
export { default as ArrowsIcon } from "./arrows";
export { default as MenuIcon } from "./menu";
export { default as ClockIcon } from "./clock";
export { default as OrderIcon } from "./order";
export { default as ReturnIcon } from "./return";
export { default as ShippingIcon } from "./shipping";
export { default as GiftIcon } from "./gift";
export { default as StudentIcon } from "./student";
