import React from "react";
// component
import { useSlider } from "components/Slider";
import { ProductCardSM, ProductCardProps } from "components/Card";
import { useTabs } from "components/Tab";

// data
import { productData } from "utils/constData";
// styled component
import {
	RelatedProductWrapper,
	SliderWrapper,
	TabContainerWrapper,
	TabTitle,
} from "./RelatedProduct.style";
import { BREAKPOINTS } from "theme/base";

// -------------------------------------------------------

const { xs, md, lg } = BREAKPOINTS;

// component generated by hoc
const options = {
	speed: 600,
	slidesPerView: 1,
	spaceBetween: 10,
	freeMode: true,
	pagination: {
		clickable: true,
		// eslint-disable-next-line @typescript-eslint/no-unused-vars
		renderBullet: (_, className) => {
			return '<span class="bulletContainer ' + className + '"> </span>';
		},
	},
	breakpoints: {
		[xs]: {
			slidesPerView: 2,
		},
		[md]: {
			slidesPerView: 4,
		},
		[lg]: {
			slidesPerView: 5,
		},
	},
};
const TabContainer = useTabs(TabTitle, TabContainerWrapper);
const ProductSlider = useSlider<ProductCardProps>(
	ProductCardSM,
	options,
	SliderWrapper
);
const RelatedProduct = () => {
	return (
		<RelatedProductWrapper>
			<TabContainer>
				<div title="Top 10 Proteins">
					<ProductSlider
						sliderData={productData.data1}
						itemOptions={{ badgeColor: "primary.regular" }}
					/>
				</div>
				<div title="Top 10 Fat Burners">
					<ProductSlider
						sliderData={productData.data2}
						itemOptions={{ badgeColor: "primary.regular" }}
					/>
				</div>
			</TabContainer>
		</RelatedProductWrapper>
	);
};
export default RelatedProduct;
