import React from "react";
// component
import { Text } from "components/Text";
import { useSlider, SliderOptions } from "components/Slider";
// redux
import { RootState, useAppSelector } from "redux/store";
// type
import { CategoryItemProps } from "types/model/category/interface";
// styled system
import { CategoryWrapper } from "./Category.style";
// slider item
import SliderItem from "./CategoryItem";

const options: SliderOptions = {
	speed: 600,
	slidesPerView: "auto",
	freeMode: true,
};

// component generated by hoc
const ProductSlider = useSlider<CategoryItemProps>(SliderItem, options);

// ------------------------------------------------------------------------

const CategoryView = ({ recentByTag }) => {
	const { taglist } = useAppSelector((state: RootState) => state.tags);

	return (
		<CategoryWrapper>
			<Text
				textTransform="uppercase"
				fontSize={15}
				padding="0 0 10px 0"
				fontWeight={900}
			>
				Categories
			</Text>
			<ProductSlider sliderData={taglist} itemOptions={{ recentByTag }} />
		</CategoryWrapper>
	);
};
export default CategoryView;
