import React, { useMemo } from "react";
// apollo
import { useQuery } from "@apollo/client";
import { BlogQuery } from "graphqls/blog";
// component
import { useSlider, SliderOptions } from "components/Slider";
import { Breadcrumbs } from "components/Breadcrumbs";
// features
import { MainBannerItem } from "widgets/BannerItem";
// type
import { BlogItemInterface } from "types/model/blog/interface";

// styled component
import {
	MainCarouselContainer,
	BreadcrumbsWrapper,
	BreadcrumbsInner,
	BannerWrapper,
} from "./VideoMainBanner.style";
import { BlogItemModel } from "types/model/blog";

const options: SliderOptions = {
	speed: 600,
	parallax: true,

	pagination: {
		clickable: true,
		// eslint-disable-next-line @typescript-eslint/no-unused-vars
		renderBullet: (_, className) => {
			return '<span class="bulletContainer ' + className + '"> </span>';
		},
	},
};
// component generated by hoc
const BannerSlider = useSlider<BlogItemInterface>(
	MainBannerItem,
	options,
	BannerWrapper
);

// -------------------------------------------------------------

const MainBannerView = () => {
	const { data } = useQuery(BlogQuery.GET_BANNER_BLOG);

	const sliderData: Array<BlogItemInterface> = useMemo(() => {
		const mostRecentBlog = data?.blogsModelCollection?.items;
		return mostRecentBlog ? mostRecentBlog.slice(0, 1) : [];
	}, [data]);

	const breadcurmbsData = [
		{ title: "home", link: "/" },
		{ title: "fittalk", link: "/" },
	];
	return (
		<MainCarouselContainer>
			<BannerSlider sliderData={sliderData} />
			<BreadcrumbsWrapper>
				<BreadcrumbsInner>
					<Breadcrumbs items={breadcurmbsData} />
				</BreadcrumbsInner>
			</BreadcrumbsWrapper>
		</MainCarouselContainer>
	);
};

export const MainBannerViewWithData: React.FC<{ param: BlogItemModel }> = ({
	param,
	...props
}) => {
	const breadcurmbsData = [
		{ title: "home", link: "/" },
		{ title: "fittalk", link: "/" },
	];
	return (
		<MainCarouselContainer>
			<MainBannerItem {...param.getOrgin()} {...props} />
			<BreadcrumbsWrapper>
				<BreadcrumbsInner>
					<Breadcrumbs items={breadcurmbsData} />
				</BreadcrumbsInner>
			</BreadcrumbsWrapper>
		</MainCarouselContainer>
	);
};

export default MainBannerView;
