import React from "react";
// component
import { SliderOptions, useSlider } from "components/Slider";
// type
import { Tag } from "contentful";
// redux
import { RootState, useAppSelector } from "redux/store";
// slider item
import SliderItem from "./CategoryItem";
// styled component
import { SearchViewWrapper } from "./CategorySearch.style";
// ----------------------------------------

// component generated by hoc
const options: SliderOptions = {
	speed: 600,
	slidesPerView: "auto",
	freeMode: true,
};

const ProductSlider = useSlider<Tag>(SliderItem, options);

const CategorySearchView = () => {
	const { taglist } = useAppSelector((state: RootState) => state.tags);
	return (
		<SearchViewWrapper>
			<ProductSlider sliderData={taglist} />
		</SearchViewWrapper>
	);
};
export default CategorySearchView;
